### Create collection
POST http://localhost:8080/collection/create
Content-Type: application/json

{
  "name": "babies",
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "age",
      "type": "int"
    }
  ],
  "parentCollection": "pandas"
}

### Insert document into collection
POST http://localhost:8080/document/insert
Content-Type: application/json

{
  "collection": "babies",
  "fields": {
    "name": "marc",
    "age": 6
  },
  "parentDocUuid": "f9d4d338-69ef-4082-87c4-e8c9f80da3e7"
}