### Create collection
POST http://localhost:8080/collection/create
Content-Type: application/json

{
  "name": "babies",
  "fields": [
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "age",
      "type": "int"
    }
  ],
  "parentCollection": "pandas"
}

### Insert document into collection
POST http://localhost:8080/document/insert
Content-Type: application/json

{
  "collection": "babies",
  "fields": {
    "name": "remo",
    "age": 3
  },
  "parentDocUuid": "574fd740-37d4-4018-80ff-c432bc39bae5"
}

### Insert document into collection
POST http://localhost:8080/query/take
Content-Type: application/json

{
  "path": [
    {
      "type": "collection",
      "name": "pandas",
      "condition": null
    },
    {
      "type": "collection",
      "name": "babies",
      "condition": null
    }
  ],
  "take": {
    "pandas": [
      "name"
    ]
  },
  "collect": [
    "babies"
  ]
}