### Create collection
POST http://localhost:8080/collection/create
Content-Type: application/json

{
  "name": "patients",
  "fields": [
    {
      "name": "first",
      "type": "string"
    },
    {
      "name": "last",
      "type": "string"
    },
    {
      "name": "age",
      "type": "int"
    }
  ],
  "parentCollection": null
}

### Create connection
POST http://localhost:8080/connection/create
Content-Type: application/json

{
  "name": "treatments",
  "collection1Name": "doctors",
  "collection2Name": "patients",
  "fields": [
    {
      "name": "since",
      "type": "int"
    }
  ]
}

### Insert connection
POST http://localhost:8080/connection/insert
Content-Type: application/json

{
  "connection": "treatments",
  "collection1Name": "doctors",
  "collection1Uuid": "20e61ebb-7981-436e-b1e6-c3dfa5d5d1c6",
  "collection2Name": "patients",
  "collection2Uuid": "750d22c1-f44f-47ed-a2fd-525df5198d8a",
  "fields": {
    "since": 2020
  }
}

### Insert document into collection
POST http://localhost:8080/document/insert
Content-Type: application/json

{
  "collection": "patients",
  "fields": {
    "first": "ignacio",
    "last": "moreno",
    "age": 70
  },
  "parentDocUuid": null
}

### Query
POST http://localhost:8080/query/take
Content-Type: application/json

{
  "path": [
    {
      "type": "collection",
      "name": "hospitals",
      "condition": null
    },
    {
      "type": "collection",
      "name": "departments",
      "condition": null
    },
    {
      "type": "collection",
      "name": "doctors",
      "condition": null
    },
    {
      "type": "connection",
      "name": "treatments",
      "condition": null
    },
    {
      "type": "collection",
      "name": "patients",
      "condition": null
    }
  ],
  "take": {
    "patients": [
      "first"
    ]
  },
  "collect": [
    "hospitals"
  ]
}

### List collecions
GET http://localhost:8080/collections/list