### Create collection
POST http://localhost:8080/collection/create
Content-Type: application/json

{
  "name": "patients",
  "fields": [
    {
      "name": "first",
      "type": "string"
    },
    {
      "name": "last",
      "type": "string"
    },
    {
      "name": "age",
      "type": "int"
    }
  ],
  "parentCollection": null
}

### Drop collection
POST http://localhost:8080/collection/drop
Content-Type: application/json

{
  "name": "patients",
  "recursive": true
}

### Drop connection
POST http://localhost:8080/connection/drop
Content-Type: application/json

{
  "name": "treatments"
}

### Create connection
POST http://localhost:8080/connection/create
Content-Type: application/json

{
  "name": "treatments",
  "collection1Name": "doctors",
  "collection2Name": "patients",
  "fields": [
    {
      "name": "since",
      "type": "int"
    }
  ]
}

### Insert connection
POST http://localhost:8080/connection/insert
Content-Type: application/json

{
  "connection": "treatments",
  "collection1Name": "doctors",
  "collection1Uuid": "20e61ebb-7981-436e-b1e6-c3dfa5d5d1c6",
  "collection2Name": "patients",
  "collection2Uuid": "750d22c1-f44f-47ed-a2fd-525df5198d8a",
  "fields": {
    "since": 2020
  }
}

### Insert document into collection
POST http://localhost:8080/document/insert
Content-Type: application/json

{
  "collection": "patients",
  "fields": {
    "first": "ignacio",
    "last": "moreno",
    "age": 70
  },
  "parentDocUuid": null
}

### Query
POST http://localhost:8080/query/get
Content-Type: application/json

{
  "path": [
    {
      "type": "collection",
      "name": "users",
      "condition": null,
      "only": null
    },
    {
      "type": "collection",
      "name": "children",
      "condition": null,
      "only": null
    }
  ]
}

### List collecions
GET http://localhost:8080/connections/list

### get schema
GET http://localhost:8080/schema